### ISSUE TITLE
会议的召开地点仅在上海吗？

### ISSUE THREAD

**Issue by doghappy** [ltm0203/dotnetconf2019_Cn#9]
抱歉，在这里开启 issue，可能不太合适，但可能是对网站的建议。

会议仅在上海召开还是计划在更多城市召开？不管前者还是后者，如果可以明确说明，有很大帮助。

**Comment by ltm0203** [comment]
目前是上海主会场，北京据悉会有一个分会场。
其他城市待定。谢谢您的关注。

**Comment by doghappy** [comment]
感谢如此快速的回复
